name: xeus-python-kernel
channels:
  - file:///home/runner/work/wasm-demo/wasm-demo/extra_packages
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - python-symengine
  - pycalphad


